# Site settings
title: truenite - Software
description: "some of my projects..."
baseurl: "" # for test: remove string '/space-jekyll-templa' to ''
url: "http://truenite.me" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.githu.io'
# User settings
username: truenite
user_title: Lorem Ipsum - FrontEnd
twitter_username: truenite
github_username:  truenite
disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# projects in header index
projects:
  - name: Codility answers
    url: https://github.com/truenite/Codility
  - name: HackerRank answers
    url: https://github.com/truenite/hackerRank
  - name: phpAutomaticDownloader
    url: https://github.com/truenite/phpAutomaticDownloader
  - name: InstUploaderRobot
    url: https://github.com/truenite/InstUploaderRobot
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
